### ISSUE TITLE
deleted old 3 files from the repo

### ISSUE THREAD

**Issue by molitona** [reewardius/bbFuzzing.txt#1]
hello, why this 3 files got deleted from the repo ?

![Screenshot from 2023-07-29 23-28-16](https://github.com/reewardius/bbFuzzing.txt/assets/35532337/646cfb6f-cbae-4a6e-b2cb-ad4b6a3f2477)

**Comment by reewardius** [comment]
I don't think it's necessary to keep them here, you can find these files on github yourself, and the normalization.txt file has lost its relevance as a file, in the readme you can find examples of how to create your own normalization.txt and use it in your projects.
